// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('.table-hover tr').hover(function() {
      return $(this).addClass('pointer');
    }, function() {
      return $(this).removeClass('pointer');
    });
    return $('.table-hover tr').click(function() {
      var $a;
      $a = $(this).find('a');
      if ($a.length) {
        return window.location.href = $(this).find('a').attr('href');
      }
    });
  });

}).call(this);
